version: '3'

services: 

    web:
        build: ./web
        expose:
            - 3000
        ports:
            - "3000:3000" # Map for now
        links:
            - evaluator:evaluator
            - postgres:postgres
        env_file: .env
        command: node index.js
    
    evaluator:
        build: ./evaluator
        expose:
            - 8000
        ports:
            - "8000:8000" # Map for now
        env_file: .env
        command: ./evaluator
    
    postgres:
        build: ./postgres
        expose:
            - 5432